.Dd 13/4/2021
.Dt hsh 1
.Sh HSH
.Nm hsh
.Nm - Holberton Shell
.Sh SYNOPSIS
.Nm
.Op filename

.Op path or pwd
/
.Nm

.Op command
|
.Nm

.Sh DESCRIPTION
    hsh is a command lenguage interpreter that executes commands from the
    standard input string, or a specified file. Commands should been written
    in bash command lenguage.
    
    .br
    hsh executes from a father shell for collecting the requiered information
    as environment variables, files given or standard input string.
    
.Sh USAGE
    Execute 
.BI hsh
    file in the simple-shell directory by positioning your prompt in
    the corresponding directory ande execute './hsh'. Finnaly have fun!
    

.Sh SUPPORTED FEATURES
.Fl
AND (&) Operator

Example: 
.Op command 1
&&
.Op command 2


.Fl
OR (|) Operator

Example: 
.Op command 1
||
.Op command 2


.Fl 
exit (also support exiting with a status)


.Fl
Environment variables management

Example:
.Op env / setenv / unsetenv


.Fl 
.Op Ctrl+c
signal


.Fl
.Op cd
command

Example:
cd
.Op path
,
cd
,
cd
.Op $HOME
,
cd
.Op ..
,
cd
.Op -


.Fl
.B ' ; '
command separator

Example:
.Op command 1
;
.Op command 2


.Fl
alias

Example:
 alias
.Op name[='value'] ...
,
alias (this will print all aliases)
,
alias name
,
alias name='value'


.Fl
Comments with #


.Fl
help command for built-ins


.Fl
Accept files as input

Example:
hsh
.Op filename


.Sh INPUT FILES
    The input file shall be a text file, except that line lengths
    shall be unlimited. If the input file consists solely of zero or
    more blank lines and comments, sh shall exit with a zero exit
    status.

.Sh AUTHORS
    Hernan Montenegro
    
    Tomas Martinez
    
.Sh SEE ALSO
.Op    Readme
https://github.com/HernanMontenegro/simple_shell/blob/main/README.md

.Op Github
https://github.com/HernanMontenegro/simple_shell
